name: Daily Stock Post

on:
  schedule:
    - cron: '30 21 * * *' # UTC 기준 (한국 시간 오전 6시 30분 실행)
  workflow_dispatch: # 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Script
        env:
          TISTORY_ACCESS_TOKEN: ${{ secrets.TISTORY_ACCESS_TOKEN }}
          TISTORY_BLOG_NAME: ${{ secrets.TISTORY_BLOG_NAME }}
        run: python main.py
